### ISSUE TITLE
fcat can't print anything in my system

### ISSUE THREAD

**Issue by federicotorrielli** [mre/fcat#39]
Hi, maybe it's some dependency that dependabot broke but my fcat is not working anymore, it gives me this error:
![fcat](https://user-images.githubusercontent.com/31370059/101240100-59ff8880-36ed-11eb-9f60-69c8fc8f2c47.png)
Thanks in advance for the support!

**Comment by mre** [comment]
Strange. That means it has problems reading from the kernel buffer or printing to the screen. 
Can you try a few different files? 
What is your kernel version and linux distribution?

**Comment by federicotorrielli** [comment]
I'm using ArcoLinux with 5.9.11-arch2-1 kernel, it gives the error on every file, even in the /home folder.

**Comment by federicotorrielli** [comment]
Any update on this?

**Comment by mre** [comment]
Unfortunately not from my side. Don't know how to debug this as I don't have any system to debug the issue. 😟 Can you try on a different distribution if you have any at hand?

**Comment by federicotorrielli** [comment]
All right! So, I did some test on a lot of distros in these days. Here's my report:

On every distribution with linux 5.9.* and 5.10.* fcat does not work BUT on every linux 5.8 and 5.4 does work without any problem.
So I guess the problem is really something that has to be related to the latest linux versions.
Tell me if you need more testing, I'll be glad to do so.

**Comment by mre** [comment]
This is utterly confusing... and a bit scary. So it sounds like something changed/broke in 5.9 (most likely changed).

**Comment by mre** [comment]
Why was that closed? I'd still say it would be interesting to know the reason why it is not working. Perhaps someone wants to pick this up in the future?

**Comment by federicotorrielli** [comment]
Well, my bad. I close issues that are more than 2 months old, because it always means that a project is currently inactive. And also the issue seems related to the new kernels so people stick with bat (which is also using the splice feature) because it's currently active and has newer features.
Can you re-open the issue? I'm currently on mobile and there's no choice to open it again here. Thanks!

**Comment by mre** [comment]
bat uses splice? That's news to me. I couldn't find any hint in the source code, only two issues, one closed and the other open but stalled.

* https://github.com/sharkdp/bat/issues/1112
* https://github.com/sharkdp/bat/issues/194

Anything I'm missing here?

**Comment by kangalio** [comment]
It seems like stdout doesn't count as a pipe anymore for some reason

`fcat file.txt | cat` works, `fcat file.txt` does not. This seems to be a common issue, e.g. [someone on StackOverflow using splice from C](https://stackoverflow.com/questions/32218381/using-splice-to-copy-file-to-stdout). It was mentioned that this issue starts with Linux 5.9, so maybe this is related?

**Comment by mre** [comment]
I looked through the [5.9 changelog](https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.9) and could only find [this patch](https://lore.kernel.org/linux-fsdevel/bfa88b5ad6f069b2b679316b9e495a970130416c.1601567868.git.josef@toxicpanda.com/), which describes a deadlock in combination with splice. Can't find much else. Maybe somebody with more kernel experience can verify.

**Comment by kangalio** [comment]
Oops, I meant to add this link to my last sentence http://archive.lwn.net:8080/linux-kernel/202105071116.638258236E@keescook/t/

**Comment by mre** [comment]
So does that mean we have to ask on the Linux Kernel mailing list if they can add back support for splice for our use-case? 😅

**Comment by mre** [comment]
I doubt they would if it's not on their roadmap already, which probably would mean this project is dead. 😆

**Comment by whoizit** [comment]
same for me
ArtixLinux (ArchLinux based), Linux 5.17.1-zen1-1-zen

```
❯ rustc -V          
rustc 1.62.0-nightly (1f7fb6413 2022-04-10)

❯ cargo install fcat
    Updating crates.io index
  Downloaded fcat v0.1.0
  Downloaded 1 crate (317.3 KB) in 1.70s
  Installing fcat v0.1.0
  Downloaded bitflags v0.9.1
  Downloaded nix v0.9.0
  Downloaded 2 crates (115.5 KB) in 1.78s
   Compiling libc v0.2.122
   Compiling bitflags v0.9.1
   Compiling cfg-if v0.1.10
   Compiling void v1.0.2
   Compiling nix v0.9.0
   Compiling fcat v0.1.0
    Finished release [optimized] target(s) in 32.79s
  Installing /home/user/.cargo/bin/fcat
   Installed package `fcat v0.1.0` (executable `fcat`)

❯ fcat --help       
thread 'main' panicked at 'fcat: --help: No such file or directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/fcat-0.1.0/src/main.rs:15:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

❯ fcat yggdrasil.conf 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EINVAL)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/fcat-0.1.0/src/main.rs:43:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mre** [comment]
Not gonna lie, it's looking pretty bleak for this project. Newer kernels changed the behavior of splice and that broke our use-case. 😕 Unless we find a workaround (or convince the maintainers to find a solution in the Kernel) this project can't be fixed.

**Comment by ConYel** [comment]
Could maybe fcat work in bsd instead?

**Comment by mre** [comment]
Yes, there's a chance. https://man.freebsd.org/cgi/man.cgi?query=splice&sektion=2&apropos=0&manpath=CentOS+7.0
The reason why it worked on Linux was that splice supported files as inputs and stdout as output. That since broke. Nowadays it's way more conservative.

One would have to try if it works on an actual BSD operating system like FreeBSD or OpenBSD.

**Comment by oech3** [comment]
I am using uutils/coreutils on Arch Linux.
uutils/cat uses a broker pipe if and only if both of in/output are not pipe and extend it to 1 MiB by fcntl:
```
$ truncate -s 1PB /tmp/huge
a@m ~> cat /tmp/huge|pv>/dev/null
^C.9GiB 0:00:01 [38.9GiB/s]
```

**Comment by mre** [comment]
I think at this point, uutils/cat is strictly superior to fcat. Not sure if there's a point in investing much time into it anymore. And I mean that in a neutral way, because we have a well-maintained, modern alternative now. But you can try to convince me of the opposite. 😃
